### ISSUE TITLE
 插件不存在时。路由中转启动时，通过RePlugin.createIntent()创建intent失败时未过滤

### ISSUE THREAD

**Issue by orange7** [yjfnypeu/Router-RePlugin#4]
Process: com.sf.park, PID: 13304
                                                             java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Intent.putExtra(java.lang.String, android.os.Parcelable)' on a null object reference
                                                                 at com.lzh.router.replugin.core.RouterBridgeActivity.start(RouterBridgeActivity.java:55)
                                                                 at com.lzh.router.replugin.core.RePluginRouteCallback$StartBridgeTask.run(RePluginRouteCallback.java:153)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                 at java.lang.Thread.run(Thread.java:764)

插件不存在，跳转就崩溃，这样是不是有点不友好

**Comment by yjfnypeu** [comment]
新发布了0.8.0版本。修复了此问题。
